config_version: v0.1
description: "Erste Version einer Konfiguration f\xFCr den Preprocessor der EvidenceSeeker\
  \ Boilerplate."
env_file: "./config/api_keys.txt"
freetext_ascriptive_analysis:
  description: Instruct the assistant to carry out free-text ascriptions analysis.
  name: freetext_ascriptive_analysis
  prompt_template: 'The following {language} claim has been submitted for fact-checking.


    <claim>{claim}</claim>


    Before we proceed with retrieving evidence items, we carefully analyse the claim.
    Your task is to contribute to this preparatory analysis, as detailed below.

    In particular, you should thoroughly discuss whether the claim makes any explicit
    ascriptions, that is, whether it explicitly ascribes a statement to a person or
    an organisation (e.g., as something the person has said, believes, acts on etc.)
    rather than plainly asserting that statement straightaway.

    If so, clarify which statements are ascribed to whom exactly and in which ways.

    In doing so, watch out for ambiguity and vagueness in the claim. Make alternative
    interpretations explicit.

    Conclude your analysis with a short list of all identified ascriptions: Formulate
    each statement in a concise manner, and such that it is transparent to whom it
    is attributed. Render the clarified ascriptions in {language}.'
  system_prompt: null
  used_model_key: null
freetext_descriptive_analysis:
  description: Instruct the assistant to carry out free-text factual/descriptive analysis.
  name: freetext_descriptive_analysis
  prompt_template: 'The following {language} claim has been submitted for fact-checking.


    <claim>{claim}</claim>


    Before we proceed with retrieving evidence items, we carefully analyse the claim.
    Your task is to contribute to this preparatory analysis, as detailed below.

    In particular, you should thoroughly discuss whether the claim contains or implies
    factual or descriptive statements, which can be verified or falsified by empirical
    observation or through scientific analysis, and which may include, for example,
    descriptive reports, historical facts, or scientific claims.

    If so, try to identify them and render them in your own words.

    In doing so, watch out for ambiguity and vagueness in the claim. Make alternative
    interpretations explicit.

    End your analysis with a short list of all identified factual or descriptive statements
    in {language}. Formulate each statement in a concise manner and such that its
    factual nature stands out clearly.'
  system_prompt: null
  used_model_key: null
freetext_normative_analysis:
  description: Instruct the assistant to carry out free-text normative analysis.
  name: freetext_normative_analysis
  prompt_template: 'The following {language} claim has been submitted for fact-checking.


    <claim>{claim}</claim>


    Before we proceed with retrieving evidence items, we carefully analyse the claim.
    Your task is to contribute to this preparatory analysis, as detailed below.

    In particular, you should thoroughly discuss whether the claim contains or implies
    normative statements, such as value judgements, recommendations, or evaluations.
    If so, try to identify them and render them in your own words.

    In doing so, watch out for ambiguity and vagueness in the claim. Make alternative
    interpretations explicit. However, avoid reading normative content into the claim
    without textual evidence.


    End your analysis with a short list of all identified normative statements in
    {language}. Formulate each statement in a concise manner and such that its normative
    nature stands out clearly.'
  system_prompt: null
  used_model_key: null
language: DE
list_ascriptive_statements:
  description: Instruct the assistant to list ascriptions.
  name: list_ascriptive_statements
  prompt_template: 'The following {language} claim has been submitted for ascriptive
    content analysis.

    <claim>{claim}</claim>

    The analysis yielded the following results:


    <results>

    {ascriptive_analysis}

    </results>


    Your task is to list all ascriptions identified in this analysis. Clearly state
    each ascription as a concise {language} statement, such that it is transparent
    to whom it is attributed. Only include ascriptions that are explicitly attributed
    to a specific person or organisation.

    Format your (possibly empty) list of statements as a JSON object.

    Do not include any other text than the JSON object.'
  system_prompt: null
  used_model_key: null
list_descriptive_statements:
  description: Instruct the assistant to list factual claims.
  name: list_descriptive_statements
  prompt_template: 'We have previously analysed the descriptive content of the following
    {language} claim:

    <claim>{claim}</claim>

    The analysis yielded the following results:


    <results>

    {descriptive_analysis}

    </results>


    Your task is to list all factual or descriptive {language} statements identified
    in the previous analysis. Only include clear cases, i.e. statements that are unambiguously
    factual or descriptive.

    Format your (possibly empty) list of statements as a JSON object.

    Do not include any other text than the JSON object.'
  system_prompt: null
  used_model_key: null
list_normative_statements:
  description: Instruct the assistant to list normative claims.
  name: list_normative_statements
  prompt_template: 'The following {language} claim has been submitted for normative
    content analysis.

    <claim>{claim}</claim>

    The analysis yielded the following results:


    <results>

    {normative_analysis}

    </results>


    Your task is to list all normative statements identified in this analysis (e.g.,
    value judgements, recommendations, or evaluations) in {language}.

    Format your (possibly empty) list of statements as a JSON object.

    Do not include any other text than the JSON object.'
  system_prompt: null
  used_model_key: null
models:
  lmstudio:
    api_key: not_needed
    backend_type: openai
    base_url: http://127.0.0.1:1234/v1/
    description: Local model served via LMStudio
    max_tokens: 1024
    model: llama-3.2-1b-instruct
    name: mllama-3.2-1b-instruct
    temperature: 0.2
    timeout: 260
  together.ai:
    api_key_name: API_TOKEN_LANGUAGE_MODEL
    backend_type: openai
    base_url: https://router.huggingface.co/together/v1
    default_headers:
      X-HF-Bill-To: DebateLabKIT
    description: Model served via Together.ai over HuggingFace
    max_tokens: 1024
    model: meta-llama/Llama-3.2-3B-Instruct-Turbo
    name: Meta-Llama-3-Instruct
    temperature: 0.2
    timeout: 260
negate_claim:
  description: Instruct the assistant to negate a claim.
  name: negate_claim
  prompt_template: 'Your task is to express the opposite of the following statement
    in plain and unequivocal language.

    Please generate a single {language} sentence that clearly states the negation.

    <statement>

    {statement}

    </statement>

    Provide only the negated statement in {language} without any additional comments.'
  system_prompt: null
  used_model_key: null
system_prompt: 'You are a helpful assistant with outstanding expertise in critical
  thinking and logico-semantic analysis. You have a background in philosophy and experience
  in fact checking and debate analysis.

  You read instructions carefully and follow them precisely. You give concise and
  clear answers.'
timeout: 900
used_model_key: together.ai
verbose: false
