config_version: v0.1
description: "Erste Version einer Konfiguration f\xFCr den ConfirmationAnalyzerConfig\
  \ der EvidenceSeeker Boilerplate."
models:
  model_1:
    api_key_name: HF_TOKEN_EVIDENCE_SEEKER
    backend_type: nim
    base_url: https://huggingface.co/api/integrations/dgx/v1
    description: "NVIDEA NIM API (kostenpflichtig \xFCber DebateLab Account)"
    max_tokens: 2048
    model: meta-llama/Llama-3.1-70B-Instruct
    name: Llama-3.1-70B-Instruct
    temperature: 0.2
  model_2:
    api_key_name: HF_TOKEN_EVIDENCE_SEEKER
    backend_type: openai
    base_url: https://api-inference.huggingface.co/v1/
    description: HF inference API
    max_tokens: 1024
    model: mistralai/Mistral-7B-Instruct-v0.2
    name: Mistral-7B-Instruct-v0.2
    temperature: 0.2
  model_3:
    api_key_name: HF_TOKEN_EVIDENCE_SEEKER
    backend_type: tgi
    base_url: https://dchi8b9swca6gxbe.eu-west-1.aws.endpoints.huggingface.cloud/v1/
    description: HF dedicated endpoint (debatelab)
    max_tokens: 2048
    model: meta-llama/Llama-3.2-3B-Instruct
    name: Llama-3.2-3B-Instruct
    temperature: 0.2
  model_4:
    api_key: no-key-required
    backend_type: tgi
    base_url: http://kriton.philosophie.kit.edu:8080/v1/
    description: Kriton@DebateLab
    max_tokens: 2048
    model: tgi
    name: "Sp\xE4tzle 8B"
    temperature: 0.2
pipeline_steps:
- claim_option: null
  description: Instruct the assistant to carry out free-text RTE analysis.
  name: freetext_confirmation_analysis
  options: null
  prompt_template: 'Determine the relationship between the following two texts:

    <TEXT>{evidence_item}</TEXT>


    <HYPOTHESIS>{statement}</HYPOTHESIS>

    Does the TEXT entail, contradict, or neither entail nor contradict the HYPOTHESIS?

    Classify the relationship as one of the following:

    Entailment: The TEXT provides sufficient evidence to support the HYPOTHESIS.

    Contradiction: The TEXT provides evidence that contradicts the HYPOTHESIS.

    Neutral: The TEXT neither supports nor contradicts the HYPOTHESIS.

    Please discuss this question thoroughly before providing your final answer.'
  system_prompt: null
  used_model_key: null
- claim_option: A
  description: Multiple choice RTE task given CoT trace.
  name: multiple_choice_confirmation_analysis
  options:
  - A
  - B
  - C
  prompt_template: 'Your task is to sum up the results of a rich textual entailment
    analysis.


    <TEXT>{evidence_item}</TEXT>


    <HYPOTHESIS>{statement}</HYPOTHESIS>


    Our previous analysis has yielded the following result:


    <RESULT>

    {freetext_confirmation_analysis}

    </RESULT>


    Please sum up this result by deciding which of the following choices is correct.
    Just answer with the label of the correct choice.


    (A) Entailment: The TEXT provides sufficient evidence to support the HYPOTHESIS.

    (B) Contradiction: The TEXT provides evidence that contradicts the HYPOTHESIS.

    (C) Neutral: The TEXT neither supports nor contradicts the HYPOTHESIS.'
  system_prompt: null
  used_model_key: model_3
system_prompt: 'You are a helpful assistant with outstanding expertise in critical
  thinking and logico-semantic analysis. You have a background in philosophy and experience
  in fact checking and debate analysis.

  You read instructions carefully and follow them precisely. You give concise and
  clear answers.'
timeout: 60
used_model_key: model_1
verbose: false
