api_key_name: HF_TOKEN_EVIDENCE_SEEKER
config_version: v0.1
description: "Erste Version einer Konfiguration f\xFCr den Retriever der EvidenceSeeker\
  \ Boilerplate."
document_input_files:
- ./IPCC_AR6_WGI_TS.pdf
embed_base_url: https://n5i1esy54f5lbm63.eu-west-1.aws.endpoints.huggingface.cloud
embed_batch_size: 32
embed_model_name: sentence-transformers/all-MiniLM-L6-v2
index_id: sentence_index
index_persist_path: storage/chunk_index
top_k: 8
window_size: 3
